import streamlit as st

st.set_page_config(
    page_title="AutoATES",
    page_icon="🏔",
    layout="wide",
)

st.title("AutoATES — Avalanche Terrain Exposure")
st.markdown(
    """
    This app presents pre-computed **Avalanche Terrain Exposure Scale (ATES)**
    classifications generated by a rule-based ATES model. 
     
    Future iterations will use the
    [AutoATES v2 model](https://nhess.copernicus.org/articles/24/1779/2024/nhess-24-1779-2024.html).

    ---

    ### What is ATES?
    ATES classifies mountain terrain into four exposure levels based on slope
    angle, runout paths, forest cover, and terrain traps:

    | Class | Label | Colour |
    |-------|-------|--------|
    | 1 | Simple | Green |
    | 2 | Challenging | Blue |
    | 3 | Complex | Black |
    | 4 | Extreme | Red |

    ---

    ### Pages

    - **Route Analysis** — Upload a GPX file to see ATES classes along your route.
    - **Area Map** — Browse the full ATES classification for a supported area.

    ---

    > **Note:** ATES ratings reflect terrain characteristics only — they do not
    > account for current snowpack or weather conditions. Always check the
    > [Avalanche Canada forecast](https://www.avalanche.ca) before heading out.
    """
)
