name: CI

on: [ push ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"
      - run: uv run --group dev pytest tests/unit
  integration-test:
    uses: ./.github/workflows/integration.yml
  # test-coverage:
  #   uses: ./.github/workflows/e2e.yml

# TODO: add linting when in next PR
